### ISSUE TITLE
Biquery - bigquery_client.query() Attribute Error

### ISSUE THREAD

**Issue by Seldakao** [googleapis/google-cloud-python#10324]
I am fetching data from bigquery by using

from google.cloud import bigquery
...
def bigquery_to_df(query):
    '''A small tool to convert the result of Bigquery to DataFrame'''

    query_job = bigquery_client.query(query)
    df = query_job.result().to_dataframe()
    return df
...
But got AttributeError which I didn't get before 
     10     query_job = bigquery_client.query(query)
---> 11     df = query_job.result().to_dataframe()
     12     return df
     13 

AttributeError: 'HTTPIterator' object has no attribute 'to_dataframe'

#### Environment details
Mac Book Pro
I used to use google-cloud-bigquery 0.28.0 and it worked fine for a long time until now. And even after I upgraded to 1.24.0 now the error still occurs.

Does anyone encounter the same issue?

**Comment by busunkim96** [comment]
@Seldakao To clarify, you experienced this issue after you upgraded from 0.28.0 to 1.24.0?

**Comment by Seldakao** [comment]
@busunkim96 Yes. I am puzzled that this function still works fine for colleague. So I killed the jupyter kernel and relaunched it, and it worked as normal. However, I don't know the root cause of the error, because it has been alright from the beginning since I installed 0.28.0 in my conda environment.
