### ISSUE TITLE
Collections deprecated in 3.10

### ISSUE THREAD

**Issue by mmuelly** [googleapis/google-cloud-python#10596]
Cloud build no longer works in python 3.10 as collections have changed.  Used for example here:
`googlecloudsdk/core/console/progress_tracker.py:651`

https://docs.python.org/3.10/whatsnew/3.10.html#collections-abc

Specific error:
`/root/google-cloud-sdk/install.sh
Welcome to the Google Cloud SDK!
WARNING: You appear to be running this script as root. This may cause 
the installation to be inaccessible to users other than the root user.
Traceback (most recent call last):
  File "/root/google-cloud-sdk/bin/bootstrapping/install.py", line 12, in <module>
    import bootstrapping
  File "/root/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "/root/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 39, in <module>
    from googlecloudsdk.core.console import progress_tracker
  File "/root/google-cloud-sdk/lib/googlecloudsdk/core/console/progress_tracker.py", line 651, in <module>
    class _BaseStagedProgressTracker(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'`

**Comment by freevatar** [comment]
I faced this issue yesterday on `Fedora 35` where `python 3.10` is default.

Here's temporary workaround:
`export CLOUDSDK_PYTHON=/usr/bin/python2`

**Comment by jesse-elentra** [comment]
Another workaround I discovered is to install Python3.8: `dnf install python3.8`
and add `export CLOUDSDK_PYTHON=/bin/python3.8` to my `.bashrc` file.
