### ISSUE TITLE
Storage: Client.download_blob_to_file fails.

### ISSUE THREAD

**Issue by shotarohorai** [googleapis/google-cloud-python#8301]
`Client.download_blob_to_file()` does not work properly when passing a URI because the parsed path which is passed as a blob name has the initial `/` .

https://github.com/googleapis/google-cloud-python/blob/master/storage/google/cloud/storage/client.py#L389-L395

It should be removed from the path before passing into a Blob constructor.
```
            scheme, netloc, path, query, frag = urlsplit(blob_or_uri)
            if scheme != "gs":
                raise ValueError("URI scheme must be gs")
            blob_name = path[1:]
            bucket = Bucket(self, name=netloc)
            blob_or_uri = Blob(blob_name, bucket)

            blob_or_uri.download_to_file(file_obj, client=self, start=start, end=end)
```

BTW: I tried to create a pull request to fix it but I was not allowed to push my commit into this repo. How can I contribute?

**Comment by tswast** [comment]
@shotarohorai Thank you for the report. Can you provide an example of a URI which does not work?

Our contributing guidelines are at https://github.com/googleapis/google-cloud-python/blob/master/CONTRIBUTING.rst. It's not expected that you would have write access to this repository, but you should be able to send a pull request from a fork.

**Comment by jakebiesinger-onduo** [comment]
@tswast no urls work. Using `client.download_blob_to_file('gs://mybucket/myobject')` will result in a `404` with a malformed url:

```
NotFound: 404 GET https://www.googleapis.com/download/storage/v1/b/mybucket/o/%2Fmyobject?alt=media: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
```
Note the leading `/` on the object name, which is becomes `%2F`.

It appears this method has never worked. It was introduced by https://github.com/googleapis/google-cloud-python/commit/e7a7bd4a2415a7a81ebaadcf7750a4c4b646ee2c and the testing there consists only of mocked file paths :(

**Comment by tom-dd** [comment]
I don't think this one is fixed, when I use the code from the documentation I get the following error (google-cloud-storage 1.17.0):
```python
 with open(file_name, 'w+') as file_obj:
        client.download_blob_to_file(
            'gs://bucket_name/path/to/blob', file_obj)
```
```
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/google/cloud/storage/client.py", line 397, in download_blob_to_file
    blob_or_uri.download_to_file(file_obj, client=self, start=start, end=end)
AttributeError: 'str' object has no attribute 'download_to_file'
```
